services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - OKTA_API_TOKEN=00r_j9n-k9dClj55Eu1b7nDbV--LgJdXemXxoz-e9z
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - vault-python-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    networks:
      - vault-python-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OKTA_ISSUER=https://dev-93127078.okta.com/oauth2/default
      - REACT_APP_OKTA_CLIENT_ID=0oaopl2m6ppzxkJX25d7
      - REACT_APP_OKTA_REDIRECT_URI=http://localhost:3000/login/callback
    networks:
      - vault-python-network

networks:
  vault-python-network:
    driver: bridge
